export const CREATE_POST = 'POSTS/CREATE_POST'
export const GET_ALL_POSTS = 'POSTS/GET_ALL_POSTS'
export const GET_POSTS_BY_ID = 'POSTS/GET_POSTS_BY_ID'
export const DELETE_POST_BY_ID = 'POSTS/DELETE_POST_BY_ID'
export const UPDATE_POST_BY_ID = 'POSTS/UPDATE_POST_BY_ID'

